# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.space_heating_enum import SpaceHeatingEnum  # noqa: E501

class TestSpaceHeatingEnum(unittest.TestCase):
    """SpaceHeatingEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpaceHeatingEnum(self):
        """Test SpaceHeatingEnum"""
        # inst = SpaceHeatingEnum()

if __name__ == '__main__':
    unittest.main()
