# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.savings import Savings  # noqa: E501

class TestSavings(unittest.TestCase):
    """Savings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Savings:
        """Test Savings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Savings`
        """
        model = Savings()  # noqa: E501
        if include_optional:
            return Savings(
                emissions = openapi_client.models.emissions.Emissions(
                    per_week = openapi_client.models.emissions_values.EmissionsValues(
                        before = 500.5, 
                        after = 100.1, 
                        difference = 400.4, ), 
                    per_year = openapi_client.models.emissions_values.EmissionsValues(
                        before = 500.5, 
                        after = 100.1, 
                        difference = 400.4, ), 
                    over_lifetime = , 
                    operational_lifetime = 15, ),
                opex = openapi_client.models.opex.Opex(
                    per_week = openapi_client.models.opex_values.OpexValues(
                        before = 500.5, 
                        after = 100.1, 
                        difference = 400.4, ), 
                    per_year = openapi_client.models.opex_values.OpexValues(
                        before = 500.5, 
                        after = 100.1, 
                        difference = 400.4, ), 
                    over_lifetime = , 
                    operational_lifetime = 15, ),
                upfront_cost = openapi_client.models.upfront_cost.UpfrontCost(
                    solar = 1.337, 
                    battery = 1.337, 
                    cooktop = 1.337, 
                    water_heating = 1.337, 
                    space_heating = 1.337, ),
                recommendation = openapi_client.models.recommendation.Recommendation(
                    action = 'SPACE_HEATING', 
                    url = 'https://www.rewiring.nz/electrification-guides/space-heating-and-cooling', )
            )
        else:
            return Savings(
        )
        """

    def testSavings(self):
        """Test Savings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
