# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.recommendation import Recommendation  # noqa: E501

class TestRecommendation(unittest.TestCase):
    """Recommendation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Recommendation:
        """Test Recommendation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Recommendation`
        """
        model = Recommendation()  # noqa: E501
        if include_optional:
            return Recommendation(
                action = 'SPACE_HEATING',
                url = 'https://www.rewiring.nz/electrification-guides/space-heating-and-cooling'
            )
        else:
            return Recommendation(
                action = 'SPACE_HEATING',
        )
        """

    def testRecommendation(self):
        """Test Recommendation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
