# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vehicle import Vehicle  # noqa: E501

class TestVehicle(unittest.TestCase):
    """Vehicle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vehicle:
        """Test Vehicle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vehicle`
        """
        model = Vehicle()  # noqa: E501
        if include_optional:
            return Vehicle(
                fuel_type = 'ELECTRIC',
                kms_per_week = 200,
                switch_to_ev = True
            )
        else:
            return Vehicle(
                fuel_type = 'ELECTRIC',
        )
        """

    def testVehicle(self):
        """Test Vehicle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
