# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.opex import Opex  # noqa: E501

class TestOpex(unittest.TestCase):
    """Opex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Opex:
        """Test Opex
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Opex`
        """
        model = Opex()  # noqa: E501
        if include_optional:
            return Opex(
                per_week = openapi_client.models.opex_values.OpexValues(
                    before = 500.5, 
                    after = 100.1, 
                    difference = 400.4, ),
                per_year = openapi_client.models.opex_values.OpexValues(
                    before = 500.5, 
                    after = 100.1, 
                    difference = 400.4, ),
                over_lifetime = openapi_client.models.opex_values.OpexValues(
                    before = 500.5, 
                    after = 100.1, 
                    difference = 400.4, ),
                operational_lifetime = 15
            )
        else:
            return Opex(
        )
        """

    def testOpex(self):
        """Test Opex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
