# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vehicle_fuel_type_enum import VehicleFuelTypeEnum  # noqa: E501

class TestVehicleFuelTypeEnum(unittest.TestCase):
    """VehicleFuelTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleFuelTypeEnum(self):
        """Test VehicleFuelTypeEnum"""
        # inst = VehicleFuelTypeEnum()

if __name__ == '__main__':
    unittest.main()
