# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CooktopEnum(str, Enum):
    """
    The main energy source for cooking
    """

    """
    allowed enum values
    """
    GAS = 'GAS'
    LPG = 'LPG'
    ELECTRIC_RESISTANCE = 'ELECTRIC_RESISTANCE'
    ELECTRIC_INDUCTION = 'ELECTRIC_INDUCTION'
    WOOD = 'WOOD'
    DONT_KNOW = 'DONT_KNOW'

    @classmethod
    def from_json(cls, json_str: str) -> CooktopEnum:
        """Create an instance of CooktopEnum from a JSON string"""
        return CooktopEnum(json.loads(json_str))


