# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class LocationEnum(str, Enum):
    """
    Where the household is located
    """

    """
    allowed enum values
    """
    NORTHLAND = 'NORTHLAND'
    AUCKLAND_NORTH = 'AUCKLAND_NORTH'
    AUCKLAND_CENTRAL = 'AUCKLAND_CENTRAL'
    AUCKLAND_EAST = 'AUCKLAND_EAST'
    AUCKLAND_WEST = 'AUCKLAND_WEST'
    AUCKLAND_SOUTH = 'AUCKLAND_SOUTH'
    WAIKATO = 'WAIKATO'
    BAY_OF_PLENTY = 'BAY_OF_PLENTY'
    GISBORNE = 'GISBORNE'
    HAWKES_BAY = 'HAWKES_BAY'
    TARANAKI = 'TARANAKI'
    MANAWATU_WANGANUI = 'MANAWATU_WANGANUI'
    WELLINGTON = 'WELLINGTON'
    TASMAN = 'TASMAN'
    NELSON = 'NELSON'
    MARLBOROUGH = 'MARLBOROUGH'
    WEST_COAST = 'WEST_COAST'
    CANTERBURY = 'CANTERBURY'
    OTAGO = 'OTAGO'
    SOUTHLAND = 'SOUTHLAND'
    STEWART_ISLAND = 'STEWART_ISLAND'
    CHATHAM_ISLANDS = 'CHATHAM_ISLANDS'
    GREAT_BARRIER_ISLAND = 'GREAT_BARRIER_ISLAND'
    OVERSEAS = 'OVERSEAS'
    OTHER = 'OTHER'

    @classmethod
    def from_json(cls, json_str: str) -> LocationEnum:
        """Create an instance of LocationEnum from a JSON string"""
        return LocationEnum(json.loads(json_str))


