# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class RecommendationActionEnum(str, Enum):
    """
    The recommended action for this household to maximise their savings
    """

    """
    allowed enum values
    """
    SPACE_HEATING = 'SPACE_HEATING'
    WATER_HEATING = 'WATER_HEATING'
    COOKING = 'COOKING'
    VEHICLE = 'VEHICLE'
    SOLAR = 'SOLAR'
    BATTERY = 'BATTERY'

    @classmethod
    def from_json(cls, json_str: str) -> RecommendationActionEnum:
        """Create an instance of RecommendationActionEnum from a JSON string"""
        return RecommendationActionEnum(json.loads(json_str))


