# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SpaceHeatingEnum(str, Enum):
    """
    The main method of space heating
    """

    """
    allowed enum values
    """
    WOOD = 'WOOD'
    GAS = 'GAS'
    LPG = 'LPG'
    DIESEL = 'DIESEL'
    ELECTRIC_RESISTANCE = 'ELECTRIC_RESISTANCE'
    ELECTRIC_HEAT_PUMP = 'ELECTRIC_HEAT_PUMP'

    @classmethod
    def from_json(cls, json_str: str) -> SpaceHeatingEnum:
        """Create an instance of SpaceHeatingEnum from a JSON string"""
        return SpaceHeatingEnum(json.loads(json_str))


