# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VehicleFuelTypeEnum(str, Enum):
    """
    VehicleFuelTypeEnum
    """

    """
    allowed enum values
    """
    ELECTRIC = 'ELECTRIC'
    PLUG_IN_HYBRID = 'PLUG_IN_HYBRID'
    HYBRID = 'HYBRID'
    PETROL = 'PETROL'
    DIESEL = 'DIESEL'

    @classmethod
    def from_json(cls, json_str: str) -> VehicleFuelTypeEnum:
        """Create an instance of VehicleFuelTypeEnum from a JSON string"""
        return VehicleFuelTypeEnum(json.loads(json_str))


