# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt
from openapi_client.models.vehicle_fuel_type_enum import VehicleFuelTypeEnum

class Vehicle(BaseModel):
    """
    Vehicle
    """
    fuel_type: VehicleFuelTypeEnum = Field(default=..., alias="fuelType")
    kms_per_week: Optional[StrictInt] = Field(default=None, alias="kmsPerWeek", description="Typical kilometres driven per week by this vehicle")
    switch_to_ev: Optional[StrictBool] = Field(default=None, alias="switchToEV", description="Whether the household wants to switch to EV")
    __properties = ["fuelType", "kmsPerWeek", "switchToEV"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Vehicle:
        """Create an instance of Vehicle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Vehicle:
        """Create an instance of Vehicle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Vehicle.parse_obj(obj)

        _obj = Vehicle.parse_obj({
            "fuel_type": obj.get("fuelType"),
            "kms_per_week": obj.get("kmsPerWeek"),
            "switch_to_ev": obj.get("switchToEV")
        })
        return _obj


