# coding: utf-8

"""
    Household savings

    This is the API for a household savings model. You can provide details about a household's energy use, and receive information about the household's potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.

    The version of the OpenAPI document: 0.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class WaterHeatingEnum(str, Enum):
    """
    The method of water heating
    """

    """
    allowed enum values
    """
    GAS = 'GAS'
    LPG = 'LPG'
    ELECTRIC_RESISTANCE = 'ELECTRIC_RESISTANCE'
    ELECTRIC_HEAT_PUMP = 'ELECTRIC_HEAT_PUMP'
    SOLAR = 'SOLAR'
    DONT_KNOW = 'DONT_KNOW'

    @classmethod
    def from_json(cls, json_str: str) -> WaterHeatingEnum:
        """Create an instance of WaterHeatingEnum from a JSON string"""
        return WaterHeatingEnum(json.loads(json_str))


