RAW_COLS = [
    "Climate change importance",
    "Living situation",
    "Living situation_Other (please specify)",
    "PV - Household_Situation",
    "Home type",
    "Home type_Other (please specify)",
    "Year built",
    "Home heating_Heat pump split system (an individual unit in a room(s))",
    "Home heating_Heat pump central system (one indoor unit for the entire home)",
    "Home heating_Gas small heater(s) (not LPG)",
    "Home heating_LPG small heater(s)",
    "Home heating_Gas fireplac(s) (not LPG)",
    "Home heating_LPG fireplace(s)",
    "Home heating_Wood fireplace(s)",
    "Home heating_Electric resistance heater (e.g. electric bar, fan, oil. ceramic panel)",
    "Home heating_Central diesel heating",
    "Home heating_Underfloor diesel heating",
    "Home heating_Underfloor electric heating",
    "Home heating_Coal heating",
    "Home heating_Other (please specify)",
    "Home heating_None",
    "Home heating_Other (please specify)_0",
    # All these number cols are as strings, like "One", "Two", .., "Five or more"
    "Home heating number_Heat pump split system (an individual unit in a room(s))",
    "Home heating number_Gas or LPG small heater",
    "Home heating number_Gas or LPG fireplace",
    "Home heating number_Electric resistance heater (e.g. electric bar, fan, oil. ceramic panel)",
    "Home heating number_Wood fireplace",
    "Home heating number_Diesel heater",
    "Water heating",
    "Cooktop_Gas cooktop",
    "Cooktop_LPG cooktop",
    "Cooktop_Electric resistance cooktop",
    "Cooktop_Electric induction cooktop",
    "Cooktop_Don't know",
    "Machinery_Lawn mower",
    "Machinery_Leaf blower",
    "Machinery_Chainsaw",
    "Machinery_Line trimmer/ whipper snipper",
    "Machinery_Pool heater",
    "Machinery_Pool pump",
    "Machinery_Motorbike/ scooter",
    "Machinery_Boat",
    "Machinery_None of these",
    "Replacements_Heat pump split system (an individual unit in a room(s))",
    "Replacements_Heat pump central system (one indoor unit for the entire home)",
    "Replacements_Gas small heater(s) (not LPG)",
    "Replacements_LPG small heater(s)",
    "Replacements_Gas fireplace (not LPG)",
    "Replacements_LPG fireplace",
    "Replacements_Wood fireplace",
    "Replacements_Electric resistance heater (e.g. electric bar, fan, oil. ceramic panel)",
    "Replacements_Central diesel heating",
    "Replacements_Underfloor diesel heating",
    "Replacements_Underfloor electric heating",
    "Replacements_Coal heating",
    "Replacements_Gas cooktop",
    "Replacements_LPG cooktop",
    "Replacements_Lawn mower",
    "Replacements_Leaf blower",
    "Replacements_Chainsaw",
    "Replacements_Line trimmer/ whipper snipper",
    "Replacements_Pool heater",
    "Replacements_Pool pump",
    "Replacements_Motorbike/ scooter",
    "Replacements_Boat",
    "Replacements_Gas water heating",
    "Replacements_LPG water heating",
    "Replacements_Electric water heating (tank/cylinder, also known as ‘resistive’)",
    "Replacements_Heat pump electric water heating",
    "Replacements_Diesel water heating",
    "Replacements_Solar water heating",
    "Replacements_",
    "Replacements_None of these",
    "Bill_Electricity",
    "Bill_Petrol (for in-home use only)",
    "Bill_Gas",
    "Bill_LPG",
    "Bill_Diesel (for in-home use only)",
    "Bill_Wood",
    "Bill_Coal",
    "COL heating home_Think about how much it costs to heat your home adequately",
    "COL heating home_Feel cold in your home because you are trying to save money",
    "COL support_Whānau/family",
    "COL support_Ministry of Social Development (MSD)",
    "COL support_Winter Energy Payment",
    "COL support_None of these",
    "COL healthy homes",
    "Warmer homes subsidy",
    "Vehicles",  # str, "One", "Two", .., "More than five"
    "Vehicles fuel/energy type_Vehicle 1",
    "Vehicles fuel/energy type_Vehicle 2",
    "Vehicles fuel/energy type_Vehicle 3",
    "Vehicles fuel/energy type_Vehicle 4",
    "Vehicles fuel/energy type_Vehicle 5",
    "Vehicles distance_Vehicle 1",
    "Vehicles distance_Vehicle 2",
    "Vehicles distance_Vehicle 3",
    "Vehicles distance_Vehicle 4",
    "Vehicles distance_Vehicle 5",
    "Vehicles fuel cost_Vehicle 1",
    "Vehicles fuel cost_Vehicle 2",
    "Vehicles fuel cost_Vehicle 3",
    "Vehicles fuel cost_Vehicle 4",
    "Vehicles fuel cost_Vehicle 5",
    "Solar",
    "Solar own/rent",
    "Solar size",
    "Solar battery",
    "Solar battery size",
    "Solar export to grid",
    "Solar export to grid fairness",
    "Solar satisfaction no battery",
    "Solar satisfaction with battery",
    "Solar NZ incentivise",
    "Solar consideration",
    "Electrifying_You would like to electrify your home further",
    "Electrifying_You would struggle to electrify your home further",
    "Electrifying_Segments",
]

# Processing

NUM_COLS_TO_CAST_TO_INT = [
    # Home heating number cols are cast to int, with "Five or more" converted to 5
    "Home heating number_Heat pump split system (an individual unit in a room(s))",
    "Home heating number_Gas or LPG small heater",
    "Home heating number_Gas or LPG fireplace",
    "Home heating number_Electric resistance heater (e.g. electric bar, fan, oil. ceramic panel)",
    "Home heating number_Wood fireplace",
    "Home heating number_Diesel heater",
    # Vehicles number col cast to int, with "More than five" converted to 6, and
    "Vehicles",
]
PROCESSED_COLS = RAW_COLS + ["space_heating_other_closest_match"]


# Enrichment

ENRICHMENT_COLS_EMISSIONS = [
    "space_heating_emissions",
    "space_heating_emissions_savings",
    "water_heating_emissions",
    "water_heating_emissions_savings",
    "cooktop_emissions",
    "cooktop_emissions_savings",
    "vehicle_emissions",
    "vehicle_emissions_savings",
    "total_emissions_without_vehicles",
    "total_emissions_without_vehicles_year",
    "total_emissions_without_vehicles_lifetime",
    "total_emissions_without_vehicles_savings",
    "total_emissions_without_vehicles_savings_year",
    "total_emissions_without_vehicles_savings_lifetime",
    "total_emissions_with_vehicles",
    "total_emissions_with_vehicles_year",
    "total_emissions_with_vehicles_lifetime",
    "total_emissions_with_vehicles_savings",
    "total_emissions_with_vehicles_savings_year",
    "total_emissions_with_vehicles_savings_lifetime",
    "emissions_savings_without_vehicles_pct",
    "emissions_savings_with_vehicles_pct",
]

ENRICHMENT_COLS_OPEX = [
    "space_heating_opex",
    "space_heating_opex_savings",
    "water_heating_opex",
    "water_heating_opex_savings",
    "cooktop_opex",
    "cooktop_opex_savings",
    "fixed_costs_yearly",
    "fixed_costs_lifetime",
    "total_opex_lifetime",
    "total_opex_savings_lifetime",
    "opex_savings_pct",
]

ENRICHMENT_COLS_UPFRONT_COST = [
    "space_heating_upfront_cost",
    "water_heating_upfront_cost",
    "cooktop_upfront_cost",
    "solar_upfront_cost",
    "total_upfront_cost",
    "total_emissions_savings_lifetime_quartile",
    "total_opex_savings_lifetime_quartile",
    "total_upfront_cost_quartile",
]

ENRICHMENT_COLS = (
    ENRICHMENT_COLS_EMISSIONS + ENRICHMENT_COLS_OPEX + ENRICHMENT_COLS_UPFRONT_COST
)

ENRICHED_COLS = PROCESSED_COLS + ENRICHMENT_COLS
